### ISSUE TITLE
Adjust difficulty levels

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-sudoku#12]
The levels in Sudoku are too hard compared to other applications and "offline" Sudokus.
The levels must be adjusted.

**Comment by alanthehat** [comment]
Some feedback from the generator to you might help (preferably using email so users can comment). 

I'm finding that some games take 3..5 minutes & some take 10 minutes.
Also, I find that there's not much difference between 'easy' & 'moderate' 

It's worth tuning this because it's the best sudoku app by a very large margin.

**Comment by Yonjuni** [comment]
We are currently integrating another difficulty level and adjusting the other. 

Information on how the levels differ can be found here: https://www.secuso.informatik.tu-darmstadt.de/en/secuso/research/results/privacy-friendly-apps/sudoku/

**Comment by Yonjuni** [comment]
New difficulty level added. Closed #12
