### ISSUE TITLE
Adding an 16x16 variant

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [SecUSo/privacy-friendly-sudoku#46]
Maybe you could add an 16x16 variant?
I find the 12x12 a bit wired because the layout is not square...

**Comment by Kamuno** [comment]
A 16x16 mode would theoretically be possible but the level generation would take too long on slow devices. Other Sudoku games just pre save a fixed number of levels.

I don't think a 16x16 board would be feasible for a release version of this app, because it is running on a lot of old devices. But you can easily implement it yourself by adding an entry to the enum. The level generation and layout should automatically be correct.

**Comment by luvarpt** [comment]
Mentioned enum is perhaps: https://github.com/SecUSo/privacy-friendly-sudoku/blob/21c2f567eed1de985314fad5c3b0a4e6ddcb8220/app/src/main/java/org/secuso/privacyfriendlysudoku/game/GameType.java#L29
